### ISSUE TITLE
How To Add Templates

### ISSUE THREAD

**Issue by simonmicheal** [swimlane/ngx-dnd#10]
Could you please show how to template a section or a draggle item. 
I would live to add some styling inputs buttons but not sure how.
Thanks

**Comment by Hypercubed** [comment]
The demo contains code for using templates with the ngx-dnd components: https://github.com/swimlane/ngx-dnd/blob/master/demo/app.component.html#L436

I would encourage you, however, to use ngx-dnd directives.  There are several examples in the demo page.

**Comment by kemalbirinci** [comment]
Hi @Hypercubed is there a new demo link about this?
