### ISSUE TITLE
Nested DND containers are no longer droppable - binding to dropZones

### ISSUE THREAD

**Issue by bostondevin** [swimlane/ngx-dnd#101]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

Nested DND containers that I used to be able to drop things between no longer work even though dropZone/dropZones are set properly. My screen is dynamically built and Dropzones are bound to a variable that is being changed dynamically as components are progressively loaded onto the screen. This all used to work fine around two weeks ago, so maybe something changed. 

**Expected behavior**

Nested DND containers should work as they are in the demo (and they used to work a couple weeks ago)

**Reproduction of the problem**

I have a working prototype of the issue up, but it's behind a login - happy to give you access somehow. PS - i' in Golden, CO - noticed you are close by in Louisville!

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Angular 6.07, CLI, Node

* **ngx-dnd version:** x.x.x

latest

* **Angular version:** 2.x.x

6.07

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by Hypercubed** [comment]
Hi @bostondevin Do you have a demo?

**Comment by gpessa** [comment]
Same here.
Angular 6.1.9

`<ngx-dnd-container [model]="nestedLists"></ngx-dnd-container>`

with this:

```
  nestedLists = [
    {
      label: 'Item 1',
      children: []
    },
    {
      label: 'Item 2',
      children: [
        {
          label: 'Item 2a',
          children: []
        },
        {
          label: 'Item 2b',
          children: []
        },
        {
          label: 'Item 2c',
          children: []
        }
      ]
    },
    {
      label: 'Item 3',
      children: [
        {
          label: 'Item 3a',
          children: []
        },
        {
          label: 'Item 3b',
          children: []
        },
        {
          label: 'Item 3c',
          children: []
        }
      ]
    }
  ];
```

**Comment by gpessa** [comment]
With the new version I have the same issue

**Comment by Hypercubed** [comment]
I cannot reproduce this... https://stackblitz.com/edit/angular-r6jj7c

**Comment by bostondevin** [comment]
This is because of the Lazy loaded module issue - where lazy loaded modules (which would be all of mine) create new DrakeStores instead of injecting one into the app module
