### ISSUE TITLE
Source Links for Builder Demo are down

### ISSUE THREAD

**Issue by Keksdroid** [swimlane/ngx-dnd#103]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**
Clicking on "Source" for Builder Demo resolves in 404 error

**Expected behavior**
I need an example for the builder demo. I want to create a nested list with draggable folders, which you can expand or collapse. Just like the section in the builder. Any tips or examples are apreciated.

**Reproduction of the problem**

Click here -> https://github.com/swimlane/ngx-dnd/blob/master/demo/app.component.html#L413

**Comment by iGreat** [comment]
https://github.com/swimlane/ngx-dnd/tree/dev/demo   
#### demo in dev branch

**Comment by Hypercubed** [comment]
Yes, with v5 we moved the files around... we will need to update the links.

**Comment by Hypercubed** [comment]
Fixes... thank you for reporting.
