### ISSUE TITLE
how to customize styles？

### ISSUE THREAD

**Issue by Tian-Hun** [swimlane/ngx-dnd#109]
"Nested Sortable - containers" Using Components how to customize styles？
```html
<ngx-dnd-container
  [model]="nestedLists">
</ngx-dnd-container>
```
or how to use "Nested Sortable - containers"  by directives

**Comment by Hypercubed** [comment]
Just a like any other CSS, if you have more specify CSS in your app, that will override the ngx-dnd styles.
