### ISSUE TITLE
Touch support / HTML5 Drag-Drop-API

### ISSUE THREAD

**Issue by reppners** [swimlane/ngx-dnd#11]
Hi I'm one of the maintainers of https://github.com/timruffles/ios-html5-drag-drop-shim/tree/rewrite which does a good job polyfilling the HTML5 Drag and Drop API for browsers/devices that don't support it natively. The rewrite is about to be released as stable and I'm using it in production for quite some time now without issues.

I don't know if there are any special cases that your module tries to solve and support but I just wanted to let you know that the mentioned polyfill is able to handle all the touch support needs so your module could rely on the HTML5 Drag and Drop API as the ground to build upon.

**Comment by mmoravcik** [comment]
Mobile support would be essential, at the moment, `ngx-dnd` example page doesn't work on mobile property

**Comment by amcdnl** [comment]
Mobile is on the roadmap

**Comment by reppners** [comment]
I've ported my favorite AngularJS drag drop directive library to Angular so whoever needs HTML5 drag and drop api support may take a look: https://github.com/reppners/ngx-drag-drop (Touch support is established with above mentioned polyfill)

**Comment by elineopsommer** [comment]
@amcdnl any updates on the mobile support?

**Comment by gs-avaddepalli** [comment]
@amcdnl any updates on mobile support?

**Comment by Hypercubed** [comment]
This is not something I've had a chance to work on recently.  During development, I tested on an iPad and everything worked as expected.  I haven't had time to do more than that.
