### ISSUE TITLE
Broken link on the demo page

### ISSUE THREAD

**Issue by earshinov** [swimlane/ngx-dnd#112]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Reproduction of the problem**

1. Visit https://swimlane.github.io/ngx-dnd/
2. Scroll to the bottom
3. Click the "View code here" link

![view code here](https://user-images.githubusercontent.com/52021/43726940-42cb7b76-99a9-11e8-9610-ec7bd6812951.png)

The link is broken:
https://github.com/swimlane/ngx-dnd/blob/master/demo/app.component.html#L413

**Comment by Hypercubed** [comment]
Fixed, thank you.

**Comment by earshinov** [comment]
Amazingly fast response. Cheers!
