### ISSUE TITLE
Not working within apps with sub-modules

### ISSUE THREAD

**Issue by fklingler** [swimlane/ngx-dnd#114]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

This package doesn't work at all inside a "feature module".
The reason is that the NgxDnDModules always includes the providers (@Injectable), and not only once in the "root" module.

Please see these guides/posts:
- https://angular.io/guide/ngmodules
- https://angular.io/guide/feature-modules
- https://angularfirst.com/the-ngmodule-forroot-convention/

The last one gives you the way to fix this. You should move the "providers" section of the @NgModule declaration inside a forRoot method. Developers using this library should use the .forRoot() method inside the "imports" of their app module, and then for each submodule that needs to use the directives/components, use the standard declaration, without the forRoot call, for the import of the module.

* **ngx-dnd version:** 5.0.6
* **Angular version:** 6.x.x

**Comment by Hypercubed** [comment]
This should be fixed in 5.1.0
