### ISSUE TITLE
Droppable accepts draggable that contains part of its id

### ISSUE THREAD

**Issue by TomDobbelaere** [swimlane/ngx-dnd#121]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**
It seems that if a draggable contains even just a part of the droppable's id, it'll accept the draggable into the container.

**Expected behavior**
You'd assume you can't drop a draggable 'lyxl' into a droppable 'xl', because they're two different id's. But it seems that in practice, because one contains part of the other, it accepts the drop?

**Reproduction of the problem**
Using the following example, we can drop the lyxl into the xl droppables, even though it doesn't contain the lyxl id. The id's don't match yet it accepts the droppable into the container.

```
<div class="ngx-dnd-container" ngxDroppable="xl">
  <div class="ngx-dnd-item" ngxDraggable="['xl']">y</div>
</div>

<div class="ngx-dnd-container" ngxDroppable="xl">
  <div class="ngx-dnd-item" ngxDraggable="['xl']">y</div>
</div>

<div class="ngx-dnd-container" ngxDroppable="lyxl">
  <div class="ngx-dnd-item" ngxDraggable="['lyxl']">lyxl</div>
</div>

<div class="ngx-dnd-container" ngxDroppable="lyxl">
  <div class="ngx-dnd-item" ngxDraggable="['lyxl']">lyxl</div>
</div>
```

**What is the motivation / use case for changing the behavior?**
In practice, this is used on a sensor monitoring platform where draggables and droppables are based on the units of sensors. The result is that I can drag a sensor with unit 'l' (liters) into a container of 'l/min' (liters per minute) for instance.

**Please tell us about your environment:**
Windows 10, Visual Studio Code, npm, Angular 6 with ng serve

* **ngx-dnd version:** x.x.x
5.0.6, I downloaded it just today so I'm assuming that's the latest version.

* **Angular version:** 2.x.x
6.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox 61.0.2 64-bit

**Comment by Hypercubed** [comment]
@TomDobbelaere Yes... without the bracks the value is a string... you need to pass an array.
