### ISSUE TITLE
Not being able to drag ngx-dnd-item(s) between ngx-dnd-containers defined in separate components lazy loaded with routing.

### ISSUE THREAD

**Issue by sn1p3** [swimlane/ngx-dnd#130]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**
Not being able to drag ngx-dnd-item(s) between ngx-dnd-containers defined in separate components lazy loaded with routing.

**Expected behavior**
Being able to drag items between ngx-dnd-container(s) displayed in by components.

**Reproduction of the problem**
https://stackblitz.com/edit/ngx-dnd-directive-example-6kqrhi

**What is the motivation / use case for changing the behavior?**
Being able to use in lazy-loaded modules  that use ngx-dnd-container(s).

**Please tell us about your environment:**
```
Angular CLI: 6.2.1
Node: 6.9.5
OS: linux x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.1
@angular-devkit/build-angular     0.8.1
@angular-devkit/build-optimizer   0.8.1
@angular-devkit/build-webpack     0.8.1
@angular-devkit/core              0.8.1
@angular-devkit/schematics        0.8.1
@angular/cdk                      6.4.7
@angular/cli                      6.2.1
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.4.7
@ngtools/webpack                  6.2.1
@schematics/angular               0.8.1
@schematics/update                0.8.1
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.17.2
```

* **ngx-dnd version:** 5.1.0

* **Angular version:** 6.1.7

* **Browser:** 
Version 69.0.3497.100 (Official Build) (64-bit)
Have not tested on other browsers

* **Language:**
Typescript 2.9.2

**Comment by sn1p3** [comment]
...
Two separate **DrakeStoreService(s)** are created when navigating to link "Not Working between module -> component" (/two) from above reproduction link ( https://stackblitz.com/edit/ngx-dnd-directive-example-6kqrhi ).

**Comment by Hypercubed** [comment]
@sn1p3... Is this any different than the change made here: https://github.com/swimlane/ngx-dnd/commit/1f7e07692902d76082a6476b7dd20a0e91910ea3

**Comment by sn1p3** [comment]
@Hypercubed Yes, it adds the ability to inject DrakeStoreService in app's module, and share it among lazy-loaded modules. The solution worked in replication example I provided, however in our application more was required. I closed the pull request; will review and resubmit if that's alright.

Thanks.

**Comment by bostondevin** [comment]
Yup - having same issue - thought I was crazy

**Comment by sn1p3** [comment]
@bostondevin What currently is working for us:

Get the project and modify: 
projects/swimlane/ngx-dnd/src/lib/ngx-dnd.module.ts

To look like:
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DraggableDirective } from './directives/ngx-draggable.directive';
import { DroppableDirective } from './directives/ngx-droppable.directive';
import { DragHandleDirective } from './directives/ngx-drag-handle.directive';
import { ContainerComponent } from './components/container/container.component';
import { ItemComponent } from './components/item/item.component';
import { DrakeStoreService } from './services/drake-store.service';
import { ModuleWithProviders } from '@angular/compiler/src/core';

const components = [ContainerComponent, ItemComponent];
const directives = [DraggableDirective, DroppableDirective, DragHandleDirective];

@NgModule({
  imports: [CommonModule],
  declarations: [...components, ...directives],
  exports: [...components, ...directives]
})
export class NgxDnDModule {
  static forRoot(): ModuleWithProviders {
  return {
    ngModule: NgxDnDModule,
    providers: [ DrakeStoreService ]
  };
}}
```

Build modified project and add it to your application at `lib/swimlane`

Then in your application's `app.module.ts`:
```
...
import { NgxDnDModule } from 'lib/swimlane/ngx-dnd';
...

@NgModule({
  imports: [...,
    NgxDnDModule.forRoot(),
  ...]
```

*Important*
In your `shared.module.ts` import and export `NgxDnDModule` without `.forRoot()`


Multiple instances of DrakeStoreService were being created, hence it was moved to `providers` in `forRoot()` and used in `app.module.ts`.

**Comment by bostondevin** [comment]
@Hypercubed is this in next release? I'm still seeing some issues
