### ISSUE TITLE
Unable to have custom child nodes, because forced to use property label.

### ISSUE THREAD

**Issue by peturh** [swimlane/ngx-dnd#141]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```
**Current behavior**
Using 
https://swimlane.github.io/ngx-dnd/#/sortables#nested-with-containers
```
<ngx-dnd-container
    [model]="nestedLists">
  </ngx-dnd-container>
```
makes it impossible to style the draggable items. My draggable nodes has the properties `title` `published` and it should have a button etc. Now it only supports `label`.

**Expected behavior**
Be able to style my nested tree myself with my own properties and buttons.

* **ngx-dnd version:** 6.0.0

* **Angular version:** 7.2.2

**Comment by Hypercubed** [comment]
If you need more control over style, etc... you need to move to using the directives: https://swimlane.github.io/ngx-dnd/#/#directives
