### ISSUE TITLE
Discard drop events when sourceModel && !draggedItem

### ISSUE THREAD

**Issue by earshinov** [swimlane/ngx-dnd#142]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**

I do not have a complete reproduction scenario, but we experience an issue of `undefined` added to the underlying array (`[model]`) when user happens to click an item when the underlying array is being modified elsewhere (by the application / parent component).

Our setup looks like this:

```
<ul class="toc-sublist ngx-dnd-container" ngxDroppable [model]="heatMaps" (drop)="handleReordering($event)">
  <li class="toc-subitem" *ngFor="let hm of heatMaps" ngxDraggable [model]="hm">
    <i class="fa fa-grip-vertical mr-1" ngxDragHandle></i>
    {{hm.caption}}
  </li>
</ul>
```

The problem is somewhere around this line:
https://github.com/swimlane/ngx-dnd/blob/master/projects/swimlane/ngx-dnd/src/lib/services/drake-store.service.ts#L156

In our case:
- `sourceModel` -- set
- `sourceModel === targetModel`
- `source === target`
- `dragIndex = -1` because at the time of the call the model does not contain `draggedItem`
- `dragElm === el` and as a result `dropElmModel` is `undefined`
- `targetModel.splice(dropIndex, 0, dropElmModel)` inserts `undefined` into the underlying array

**Expected behavior**

ngx-dnd should contain guards against this behavior.

I may be mistaken, but replacing this line:

```
const hasDragModel = !!(sourceModel && draggedItem);
```

with

```
if (sourceModel && !draggedItem)
  return;
const hasDragModel = !!sourceModel
```

should fix the issue.

**Reproduction of the problem**

If needed, I can try to reproduce the issue in https://plnkr.co.

**What is the motivation / use case for changing the behavior?**

Better stability.

**Please tell us about your environment:**

* **ngx-dnd version:** 6.0.0
* **Angular version:** 7.0.0
* **Browser:** Seen in Chrome 72.0.3626.119 (Official Build) (64-bit)
* **Language:** TypeScript 3.1.3

**Comment by earshinov** [comment]
OK, it seems that I missed a crucial detail: in addition to array items, we also have a button inside the ngxDroppable container. It is not clear from the docs whether having a non-ngxDraggable element inside ngxDroppable is supported, but this seems to be the root of the problem.

Here is the demo:
https://stackblitz.com/edit/ngx-dnd-142?file=src/app/app.component.html

```
<ul ngxDroppable [model]="items">
  <li *ngFor="let item of items" ngxDraggable [model]="item">
    {{item.name}} <span style="cursor: pointer" (click)="remove(item)">✗</span>
  </li>
  <li><button type="button" (click)="add()">+</button></li>
</ul>
```

Keep adding and removing items. At some point you will get 

```
ERROR TypeError: Cannot read property 'name' of undefined
    at Object.eval [as updateRenderer] (AppComponent.html:2)
    at Object.debugUpdateRenderer [as updateRenderer] (services.ts:409)
```

error when pressing [+]

**Comment by earshinov** [comment]
Things are even simpler. I have updated the demo page:
https://stackblitz.com/edit/ngx-dnd-142

```
<ul ngxDroppable [model]="items">
  <li *ngFor="let item of items" ngxDraggable [model]="item">{{item.name}}</li>
  <li>Non-draggable</li>
</ul>
```

Try dragging the non-draggable item and you will see the error.

**Comment by Hypercubed** [comment]
I'm afraid that's how the underlying dnd lib works.  I might be able to work around this but for now your best option is to use the "[moves]" tag for things you don't want draggable:

```
<ul ngxDroppable [model]="items">
  <li *ngFor="let item of items" ngxDraggable [model]="item">{{item.name}}</li>
  <li ngxDraggable [moves]="false">Non-draggable</li>
</ul>
```

**Comment by earshinov** [comment]
@Hypercubed, thank you for the clarification.

I cannot find any mention of the `moves` input in the [README](https://github.com/swimlane/ngx-dnd) and the [docs](https://github.com/swimlane/ngx-dnd). Is it documented?

**Comment by Hypercubed** [comment]
It's under the ngxDraggable directive API: https://swimlane.github.io/ngx-dnd/#/directives/draggableDirective#draggabledirective
