### ISSUE TITLE
Does ngx-dnd support SVG Drag and Drop?

### ISSUE THREAD

**Issue by samheihey** [swimlane/ngx-dnd#148]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**
Drag and drop works flawlessly on divs and some other components, but not on svg such as rect, polygon, etc...

**Expected behavior**
Drag and drop works on svg elements

**Reproduction of the problem**
N/A

**What is the motivation / use case for changing the behavior?**
To drag and drop SVG elements

**Please tell us about your environment:**
N/A

* **ngx-dnd version:** N/A

* **Angular version:** 6 & 7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by Hypercubed** [comment]
I think that is out of scopr for this project.
