### ISSUE TITLE
How Can I apply droppableItemClass  for containers not for items?

### ISSUE THREAD

**Issue by Souvik93** [swimlane/ngx-dnd#15]

**Comment by Hypercubed** [comment]
Please provide an example.

**Comment by Souvik93** [comment]
I am getting  "_co.droppableItemClass" is not a fuction error. 
``
<ngx-dnd-container
           
            [model]="targetBuilderTools"
            dropZone="builder-target"
            [removeOnSpill]="true"
                   [droppableItemClass]="'col4'"       
            (drag)="log($event)"
            (drop)="log($event)"
            (over)="log($event)"
            (out)="log($event)"
            (remove)="log($event)">
</ngx-dnd-container> 
``

**Comment by Hypercubed** [comment]
In the last published version (2.1.2) droppableItemClass must be a function.  I have the ability to use a string value in the master code... but it has not been published yet.

**Comment by Souvik93** [comment]
Ok. Thanks :)
