### ISSUE TITLE
deploy with ivy

### ISSUE THREAD

**Issue by GlauberF** [swimlane/ngx-dnd#150]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**
"@swimlane/ngx-dnd": "8.0.0",

**Reproduction of the problem**
Cannot combine @Input decorators with query decorators

**Comment by Hypercubed** [comment]
Thank you @GlauberF
