### ISSUE TITLE
Angular9 support

### ISSUE THREAD

**Issue by hijamoya** [swimlane/ngx-dnd#154]
```
ERROR in Failed to compile entry-point @swimlane/ngx-dnd (es2015 as esm2015) due to compilation errors:
node_modules/@swimlane/ngx-dnd/fesm2015/swimlane-ngx-dnd.js:767:33 - error NG1006: Cannot combine @Input decorators with query decorators
```
```
node_modules/@swimlane/ngx-dnd/fesm2015/swimlane-ngx-dnd.js:958:31 - error NG6001: The class 'ContainerComponent' is listed in the declarations of the NgModule 'NgxDnDModule', but is not a directive, a component, or a pipe.
```
Please upgrade to support angular9 app.

**Comment by yakimko** [comment]
@Hypercubed any updates on this?

**Comment by jlbates** [comment]
For what it's worth, you can quite easily replace this library with the @angular/cdk/drag-drop library for angular 9 support.

**Comment by yakimko** [comment]
@jlbates it does not support nested components

**Comment by Hypercubed** [comment]
We've been using ngx-dnd with ng9 for sometime.  Can you verify you have installed latest?

**Comment by hijamoya** [comment]
I saw this commit:
https://github.com/swimlane/ngx-dnd/commit/dcb5990388dbd5867bd14cf1202a1637f424367b
But there is no corresponding release for it.

**Comment by Hypercubed** [comment]
The specific issue reported was fixed here: https://github.com/swimlane/ngx-dnd/pull/151 and released in v8.1.  Lease make sure you have ngx-dnd@v8.1 installed.

**Comment by ozeltser** [comment]
I have this crash happening with 
    "@swimlane/ngx-dnd": "^8.1.0",
in my package.json
Error: Failed to compile entry-point @swimlane/ngx-dnd (esm5 as esm5) due to compilation errors:
node_modules/@swimlane/ngx-dnd/esm5/lib/ngx-dnd.module.js:36:35 - error NG1010: Expected array when reading the NgModule.declarations of NgxDnDModule

36                     declarations: tslib_1.__spread(components, directives),

**Comment by kishorpawar** [comment]
For me I got the following warning before compilation start, but compilation still succeed without any error. 

> Warning: Entry point '@swimlane/ngx-dnd' contains deep imports into '../node_modules/@angular/compiler/src/core'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by Hypercubed** [comment]
The deep imports warning has been fixed.
