### ISSUE TITLE
Error in polyfills after migrate on angular 9

### ISSUE THREAD

**Issue by vaydich** [swimlane/ngx-dnd#158]
Hi.

After migrate on angular 9 while ng serve i face with error

ERROR in src/polyfills.ts:93:3 - error TS2739: Type 'Window & typeof globalThis' is missing the following properties from type 'Global': Buffer, GLOBAL, root, gc

<img width="813" alt="Screenshot 2020-04-06 at 13 06 36" src="https://user-images.githubusercontent.com/12065515/78552051-77531e80-780f-11ea-91b6-7064ece30063.png">

in my polyfill file as you recommend i put

if (typeof window['global'] === 'undefined') {
  window['global'] = window;
}

Can you explain me what's the problem?

**Comment by stuartaccent** [comment]
Hi @vaydich,

Before I go trawling round the internet, did you ever fix this?

Tnx, Stu

**Comment by Hypercubed** [comment]
See if this helps: https://github.com/swimlane/ngx-dnd/blob/master/src/polyfills.ts#L83
