### ISSUE TITLE
Angular 9 | deep imports

### ISSUE THREAD

**Issue by GlauberF** [swimlane/ngx-dnd#160]
Warning: Entry point '@swimlane/ngx-dnd' contains deep imports into '/var/www/html/pwa-vimbo-new/node_modules/@angular/compiler/src/core'. This is probably not a problem, but may cause the compilation of entry points to be out of order

**Comment by GlauberF** [comment]
any news ?

**Comment by SamuelMS** [comment]
This looks to be fixed in `8.1.2`, per comments in #161.

**Comment by GlauberF** [comment]
@SamuelMS Thanks.
