### ISSUE TITLE
Automating a drag and drop

### ISSUE THREAD

**Issue by spencermayne** [swimlane/ngx-dnd#164]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

I have recently started using ngx-dnd for a feature in my product, and have started to try and add some automated tests. The issue I am running in to is being able to programmatically trigger a drag and drop successfully. I am using native JS for this, with DragEvents:

Simulate fn:
```
var srcElement = document.querySelector('your source element selector')
var trgElement = document.querySelector('your target element selector')

/*Simulating drag start*/
var type = 'dragstart';
var dragEvent= new DragEvent(type, {dataTransfer: new DataTransfer()});
dragEvent.dataTransfer.effectAllowed = 'all';
this.dispatchEvent(srcElement , type, dragEvent);

/*Simulating drop*/
type = 'drop';
var dropEvent = new DragEvent(type, {dataTransfer: dragEvent.dataTransfer});
this.dispatchEvent(trgElement, type, dropEvent);

/*Simulating drag end*/
type = 'dragend';
var dragEndEvent = new DragEvent(type, {dataTransfer: dragEvent.dataTransfer});
this.dispatchEvent(srcElement, type, dragEndEvent);
```

dispatchEvent fn:
```
if (elem.dispatchEvent) {
    elem.dispatchEvent(event);
} else if (elem.fireEvent) {
    elem.fireEvent("on" + type, event);
}
```

The drop event triggers fine, but the drag event is not, thus the drop event being useless. Is there a specific way to trigger a drag event on a node?

**What is the motivation / use case for changing the behavior?**
To provide automated tests for the feature

**Please tell us about your environment:**
Windows 10. VS Code. 

* **ngx-dnd version:** x.x.x
8.0.0

* **Angular version:** 2.x.x
8.1.1

* **Browser:** 
Chrome 83.0.4103.97

* **Language:**
TS: 3.4.5

**Comment by Hypercubed** [comment]
In our automation tests we are using `mousedown`, `mousemove`, and `mouseup` events to simulate drag and drop.... you might want to take a look at those: https://github.com/swimlane/ngx-dnd/blob/master/cypress/integration/ngx-dnd_spec.js
