### ISSUE TITLE
Release with support for Angular 11

### ISSUE THREAD

**Issue by gabrielmaldi** [swimlane/ngx-dnd#181]
Hi,

Is a new release planned now that support for Angular 11 has been merged (https://github.com/swimlane/ngx-dnd/pull/177)?

Thanks!

**Comment by Tea-Ice** [comment]
@Hypercubed Any progress on making a release? I use this package extensively, and the angular upgrades would really be appreciated.

**Comment by Hypercubed** [comment]
Released as v9.
