### ISSUE TITLE
Angular 12 Upgrade

### ISSUE THREAD

**Issue by Tea-Ice** [swimlane/ngx-dnd#189]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

It gives Peer Dependency Errors

**Expected behavior**

It to not do that

**Reproduction of the problem**

Use with Angular 12

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-dnd version:** 9.0.0

* **Angular version:** 12
* 

* **Browser:** [all]

* **Language:** [all]

**Comment by Hypercubed** [comment]
Coming soon
