### ISSUE TITLE
Angular 12 Upgrade Release (PR already exists)

### ISSUE THREAD

**Issue by Tea-Ice** [swimlane/ngx-dnd#199]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**
Peer dependency issues with Angular 12 and latest npm.

**Expected behavior**
Not getting this

**Reproduction of the problem**
Use with Angular 12

**What is the motivation / use case for changing the behavior?**
Angular 12

**Please tell us about your environment:**

* **ngx-dnd version:** x.x.x

* **Angular version:** 2.x.x
12

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

There is already a PR for this, so I think you just need to make a release

**Comment by AliKholmatov** [comment]
@nelsonGuti @haeminn Hi! Could you help with upgrading ?

**Comment by 6matko** [comment]
Hi.
Any ETA on this one ?

**Comment by vgb1993** [comment]
Hi there, we also need to upgrade and this seems to be my only dependeny blocking us. Any updates?

**Comment by princehorn** [comment]
We are also very interested that this PR will be merged. @nelsonGuti can you effort some time for this review?

**Comment by Hypercubed** [comment]
@vgb1993 

Are there any paricular issues you are having running the current release?  It should work fine with Angular 12 and 13.
