### ISSUE TITLE
How to achieve the same setup as "Nested Sortable - containers", but using directives and my own styles?

### ISSUE THREAD

**Issue by nechita** [swimlane/ngx-dnd#23]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here
```
How can I achieve the same setup as "Nested Sortable - containers", but using directives and my own styles?

**Comment by elineopsommer** [comment]
Any updates on this? A lot of the advanced part is only documented for components

**Comment by Hypercubed** [comment]
Please see the post and the example here: #44
