### ISSUE TITLE
What is the license on this?

### ISSUE THREAD

**Issue by alignsoft** [swimlane/ngx-dnd#24]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] licence request
[ ] support request => Please do not submit support request here
```

What is the license on this? It looks really promising, and I'd really like to use it as it checks a bunch of boxes on a project I'm working on currently, but I can't touch it without an posted open source license (ideally MIT).

Thanks!

**Comment by Hypercubed** [comment]
MIT.  It's in the package.json... https://github.com/swimlane/ngx-dnd/blob/master/package.json#L53  We should make it more clear.

**Comment by alignsoft** [comment]
Fantastic - thank you! I always/only look for a license file in the repo itself, I'd honestly never thought to go package diving. Cheers!
