### ISSUE TITLE
Feature - Drag container and drop group of items in another container

### ISSUE THREAD

**Issue by gamefundas** [swimlane/ngx-dnd#28]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```
I have a use case where the items from one container have to be dropped on another to merge the contents together.  I noticed the examples kind of nests the dragged container. This prevents me to move a group of items together in to another container.

Is there any way I can accomplish this with minimal coding.

Thanks
Andy

**Comment by Hypercubed** [comment]
Can you provide an example plunker with what you are attempting?
