### ISSUE TITLE
Include in the docs the need to add reference to @swimlane/ng-dnd/release/index.css

### ISSUE THREAD

**Issue by billyboingo** [swimlane/ngx-dnd#29]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Following the documentation, drag and drop works but looks nothing like the demos, with the currently dragging element showing up at the bottom of the container and not sticking to the pointer.

**Expected behavior**
I expect the results from the demo when I follow the installation and code samples.

**Reproduction of the problem**
Start a fresh angular project, create a feature module using ngx-dnd, install following the documentation and use the demo code.

**What is the motivation / use case for changing the behavior?**
The documentation needs to give ALL of the steps needed to install the module and have it work correctly.

**Please tell us about your environment:**

I'm using VSCode running on Windows 10 for development.

* **ngx-charts version:** x.x.x

* **Angular version:** 4.3.4

* **Browser:** all 

* **Language:**  TypeScript 2.4.2

**Comment by Hypercubed** [comment]
Done... thank you.
