### ISSUE TITLE
Drag and drop bugs in horizontal layout

### ISSUE THREAD

**Issue by Mr-dk** [swimlane/ngx-dnd#30]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

![avatar](https://raw.githubusercontent.com/Mr-dk/MarkDownImages/master/issue/1.png)
**Expected behavior**

Insert to the end

**Comment by Hypercubed** [comment]
Make sure the droppable container has some space to drop items.  This should work if it does not please provide a plunker.
