### ISSUE TITLE
No Drag Visuals

### ISSUE THREAD

**Issue by jrodl3r** [swimlane/ngx-dnd#34]
Everything appears to be working fine, but the drag-handle, or "ghost" drag element is not appearing on the mouse or touch locations when I start dragging an item. The item just appears below the list and never moves until the drop event is fired.

Am I missing a style include somewhere or something? Thx!

**Comment by Hypercubed** [comment]
Can you share a repo or a plunker?

**Comment by Abhay-Bitloka** [comment]
Facing same issue. Is there a workaround for this?

**Comment by cedWetzel** [comment]
When using directive style you have to provide the CSS by yourself. 
To get the default behavior try 
```
.gu-mirror {
  position: fixed !important;
  margin: 0 !important;
  z-index: 9999 !important;
  opacity: 0.8;
  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
  filter: alpha(opacity=80);
}
```
(source https://github.com/swimlane/ngx-dnd/blob/master/src/components/item/item.component.scss#L28 )

**Comment by Hypercubed** [comment]
As @cedWetzel said, you need to BYO styles or include `@swimlane/ng-dnd/release/index.css`

**Comment by gs-rthati** [comment]
@cedWetzel couldn't drop the element after adding the mentioned style because mouseover is not happening on droppable area

**Comment by gs-rthati** [comment]
@Hypercubed including the stylesheet is also not working FYI
