### ISSUE TITLE
Support for Angular 5.0.0

### ISSUE THREAD

**Issue by WandererInVoids** [swimlane/ngx-dnd#36]
I'm submitting a

[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here

(remove/update deprecated code )

**Comment by srcn** [comment]
Can we have a tag for v3.1.0 so we can update our dependencies..

**Comment by WandererInVoids** [comment]
sorry i can`t publish(no access) use my if u want @wandererin/ngx-dnd

**Comment by retailify** [comment]
Could you please tag, build and upload the npm for Angular 5?
Thank you!

**Comment by Hypercubed** [comment]
All, I am working in this.  I am having an issue publishing ATM.

**Comment by Hypercubed** [comment]
This should be published, reopen if you have issues... Thanks.
