### ISSUE TITLE
I want to specify a drag target

### ISSUE THREAD

**Issue by CREPAAS** [swimlane/ngx-dnd#4]
I want ngxDraggable directive target drag then siblings or parent element drag
What should I do?

![image](https://cloud.githubusercontent.com/assets/14234215/25324900/62424c36-2903-11e7-9e37-048148f23bdd.png)

**Comment by Hypercubed** [comment]
I'm sorry, I don't understand the question.

**Comment by CREPAAS** [comment]
@Hypercubed 
I mean when i drag child elements on one element ( ex) Item 1 ), i wanna make it moves whole element.

**Comment by Hypercubed** [comment]
Do you mean a drag handle?  I am working on that.

**Comment by Hypercubed** [comment]
Drag handles are in the latest version.  You can see the demo code here:  https://github.com/swimlane/ngx-dnd/blob/master/demo/app.component.html#L33 .  Please reopen if this is not what you were thinking.
