### ISSUE TITLE
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template

### ISSUE THREAD

**Issue by walkover101** [swimlane/ngx-dnd#40]
Getting this error in Angular 5.0

**Comment by WandererInVoids** [comment]
@walkover101 its same  https://github.com/swimlane/ngx-dnd/issues/36

**Comment by vksgautam1** [comment]
same issue here..

**Comment by Hypercubed** [comment]
@vksgautam1 ensure you are using ngx-dnd v3.1.

**Comment by e06widu** [comment]
ngOutletContext has been removed as it was deprecated since v4. Use ngTemplateOutletContext instead of ngOutletContext in angular 5

**Comment by Hypercubed** [comment]
It has been fixed in v3.1 and, as of today, in the demo.

**Comment by tupham** [comment]
Hi everyone, is release 3.1 available to download
