### ISSUE TITLE
Support for Internet Explorer 11

### ISSUE THREAD

**Issue by ElodieBergonnier** [swimlane/ngx-dnd#42]
I think there is a bug with the drop event in **nested sortable** with **Internet Explorer 11**.

You can reproduce the bug on the demo page ([https://swimlane.github.io/ngx-dnd/]), in the "Nested Sortable" example.
When I try to move the item 3b in first the block (after item 1a), the drop event is not triggered.

Thank you for your help and for your fantastic library!
Elodie

**Comment by Werner-Dohse** [comment]
Console logs show that the nested drop causes the following error:
"Object doesn't support property or method 'append' "

Not sure if there is a polyfill available for somewhere for this?

**Comment by jarodsmk** [comment]
Looking at the code on the live demo at the time of writing this, the error is thrown on line 69992:

`// add element back, let angular remove it`
                                    `source.append(el);`

Implying that Edge & IE11 can't pickup the 'source' param of Dragula's `.on('drop',...` event

**Comment by Hypercubed** [comment]
In the latest release, this has been changed to `appendChild`.  The web demo might be behind.  Closing.

**Comment by jarodsmk** [comment]
We're currently on 3.1.0, but if we run:
`npm uninstall @swimlane/ngx-dnd`
`npm install @swimlane/ngx-dnd@3.1.1`
the response is:
`No matching version found for @swimlane/ngx-dnd@3.1.1`

Or 
`npm install @swimlane/ngx-dnd@latest`
returns 3.1.0

**Comment by jarodsmk** [comment]
Yea, you need to publish to NPM please

**Comment by TheGlockZentix** [comment]
Any updates on this?

**Comment by Werner-Dohse** [comment]
@Hypercubed just had a look and the npm version is still on 3.1.0. Any idea when 3.1.1 will be updated on npm?

**Comment by Hypercubed** [comment]
Published as v3.1.2, not sure what happened to 3.1.1.

**Comment by jarodsmk** [comment]
Thanks a ton!
