### ISSUE TITLE
Documentation for directives

### ISSUE THREAD

**Issue by elineopsommer** [swimlane/ngx-dnd#45]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

Need more documentation to build the model for using with directives, now a lot is shown using the components..

**Comment by Hypercubed** [comment]
Which example would you like to see using directives?

**Comment by elineopsommer** [comment]
@Hypercubed I would like to see the nested sortable + with containers

**Comment by Hypercubed** [comment]
I believe you have what you need here #44
