### ISSUE TITLE
How can I make scrolling working when dragging

### ISSUE THREAD

**Issue by newdevsoft7** [swimlane/ngx-dnd#46]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here
```

**Current behavior**
I have lots of draggable items on a page, so the page has a vertical scrollbar. but when I drag an element and move to the top or bottom of the visible area, scrolling doesn't work.
Did anyone solve this problem before? Thanks for your help.

**Comment by bharathmuppa** [comment]
why this issue is closed? @newdevsoft7 newdevsoft7

**Comment by FranciZ** [comment]
@newdevsoft7 Did you manage to resolve the issue? If so, would you mind sharing please.

**Comment by ramtel2005** [comment]
@newdevsoft7 you can share the code, so issue is resolved for every one.
