### ISSUE TITLE
[question] Events when using directive, not component

### ISSUE THREAD

**Issue by ssuperczynski** [swimlane/ngx-dnd#50]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Sorry, will will not be able to answer every support request.  Please consider other venues for support requests
```

Is it possible to listen on events:
```ts
(drag)="log($event)"
(drop)="log($event)"
(over)="log($event)"
(out)="log($event)"
(remove)="log($event)"
```

 when using `ngxDraggable` directive instead of `<ngx-dnd-container>` component?

**Current behaviour**

```html
<div class="ngx-dnd-container" ngxDroppable>
  <div class="ngx-dnd-item" ngxDraggable>Item 1</div>
  <div class="ngx-dnd-item" ngxDraggable>Item 2</div>
  <div class="ngx-dnd-item" ngxDraggable>Item 3</div>
</div>
```

**Expected behavior**
?
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-dnd version:** 3.1.0

* **Angular version:** 5.2.0

* **Browser:** Chrome 64

* **Language:**

**Comment by ssuperczynski** [comment]
Found it:

```html
<div
  class="ngx-dnd-container"
  (drag)="log($event)"
  (drop)="log($event)"
  (over)="log($event)"
  (out)="log($event)"
  (remove)="log($event)"
  ngxDroppable>
  <div class="ngx-dnd-item" ngxDraggable>Item 1</div>
  <div class="ngx-dnd-item" ngxDraggable>Item 2</div>
  <div class="ngx-dnd-item" ngxDraggable>Item 3</div>
</div>
```

**Comment by calebeaires** [comment]
@ssuperczynski Your implementation works like a charm, but I would like to get `value` object by using `[model]` input. Without ngx-dnd component (on directive)`value` object from `$event` is undefined
