### ISSUE TITLE
Form Array sortable with ngx-dnd

### ISSUE THREAD

**Issue by NumericFactory** [swimlane/ngx-dnd#51]
I try to play with form Array in Angular5. 
I create a list of forms with form Array and i want the use can reorganize them with ngx-dnd 

```
// ... into the forms : my formArray "lines" (formData is a getter which returns this.form.get('lines');
<div class="ngx-dnd-container" ngxDroppable [model]="formData.controls">
    <div class="ngx-dnd-item" ngxDraggable [model]="line" formArrayName="lines" *ngFor="let line of formData.controls; let i = index;">
        <div [formGroupName]="i">
            <textarea formControlName="linedescription"></textarea>
        </div>
    </div>
</div>
```
TEST HERE : https://angular-xqhjug.stackblitz.io

**The problem is**  : 
- This code works fine IF the user type into textarea AFTER he drags and drop
- This code doesn't work IF the user JUST drag and drop (in this case my form Array "lines" is the same that before drag and drop to change order)

**Questions**  : 
1 Do you know how to use correctly ng-dnd with form Array (i have the index of form in array in my template)
2 Can i use a "callback method" of ng-dnd in my Component ? (to execute something after "drop")

Thanks.
**Fred** from Paris, France

**Comment by NumericFactory** [comment]
Ok i found solutions and i give you this one !

 **1 ngx-dnd events**

ngx-dnd library allows us to use many events : drop(), drag(), over(), out(), remove(), cancel()

https://github.com/swimlane/ngx-dnd/blob/master/src/directives/ngx-droppable.directive.ts#L36

So, you can call your own method in your component if an item is "dropped". Example :

*in your form.component.html*

    <div (drop)="dropped($event)" 
         class="ngx-dnd-container" 
         ngxDroppable 
         [model]="formData.controls">
    //...

*in your form.component.ts*

    dropped(event) {
        alert('Ok drop is Donne !')
    }


 **2 Update formArray**
The problem was here : our "drop action" didn't re-order the formArray
Angualar formArray class expose many methods to solve this problem
https://angular.io/api/forms/FormArray

I choise the reset() method cause we can pass value in parameters and update the entire formArray.

> reset(value?: any, options?: Object)

*Finally, update your méthod in your form.component.ts*

    dropped(event) {
        let linesCopy = [];
        this.lines = this.form.get('lines') as FormArray;
        for(let line of this.lines.controls) {
            linesCopy.push(line.value);
        }
        console.log(linesCopy);
        console.log(this.lines.value);
        this.lines.reset(linesCopy);
    }

> Oh It works correctly now ! You can check here =>
> https://angular-xqhjug.stackblitz.io

PS: Be careful to use only form class methods when you manipulate forms in Angular. Dont'use JS methods to push, remove, set value, etc...
formArray Class => https://angular.io/api/forms/FormArray

Frederic LOSSIGNOL, leadDev from Paris, France

**Comment by prashant-shilimkar** [comment]
Hi, @NumericFactory Do you have plunker for your example?
