### ISSUE TITLE
Using the library with Angular 5. Works great on Chrome & Edge browsers but cannot get it to work on internet explorer. It drags but does not drop. Can it be made to work on internet explorer?

### ISSUE THREAD

**Issue by fortesl** [swimlane/ngx-dnd#55]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by crutchcorn** [comment]
In my tests with IE11 - it seems to work fine. Which version of IE are you having problems with?

**Comment by fortesl** [comment]
This is no longer an issue for me. Thanks

**Comment by heindykunadi** [comment]
@fortesl what did you do to solve this issue? I am also having the same problem on my end. IE 11
