### ISSUE TITLE
ngxDragHandle with [ngxDraggable]

### ISSUE THREAD

**Issue by nyn0x** [swimlane/ngx-dnd#57]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```
( maybe is a support request ? =\ )

**Current behavior**

ngxDragHandle doesn't work if the 'ngDraggable' directive is wrapped in brackets.
**Expected behavior**

same behavior as if 'ngDraggable' didn't have brackets.

**Reproduction of the problem**

Here a small example: [https://stackblitz.com/edit/angular-6esdtm](https://stackblitz.com/edit/angular-6esdtm)
I can drag and drop DIV while I used ngxDragHandle

**What is the motivation / use case for changing the behavior?**

To make my component reusable with another name zone:
I pass the names of the zones by 'Input ()' and sometime I use conditions in '[ngxDraggable]'.

**Please tell us about your environment:**

* **Angular version:** 5.2.5

* **Browser:** [Chrome XX]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Hypercubed** [comment]
In that case pass the zones to the draggable using `[dropZones]=".."`
