### ISSUE TITLE
angular cli: AOT does not work

### ISSUE THREAD

**Issue by Gerros** [swimlane/ngx-dnd#6]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
when using the angular cli and AOT than the following error appears:

ERROR in ENOENT: no such file or directory, open 'D:\ccviews\*******\src\main\ui\node_modules\@swimlane\ngx-dnd\release\components\container\container.component.html'

ng build works
ng build --aot leads to the error

**Expected behavior**
ng build should work with as well as without aot

"dependencies": {
    "@ angular/animations": "4.1.2",
    "@ angular/common": "4.1.2",
    "@ angular/compiler": "4.1.2",
    "@ angular/core": "4.1.2",
    "@ angular/forms": "4.1.2",
    "@ angular/http": "4.1.2",
    "@ angular/platform-browser": "4.1.2",
    "@ angular/platform-browser-dynamic": "4.1.2",
    "@ angular/router": "4.1.2",
    "@ ng-bootstrap/ng-bootstrap": "1.0.0-alpha.25",
    "@swimlane/ngx-datatable": "9.1.0",
    "@swimlane/ngx-dnd": "2.1.2",
    "core-js": "2.4.1",
    "dragula": "3.7.2",
    "file-saver": "1.3.3",
    "ng2-dragula": "1.3.1",
    "rxjs": "5.4.0",
    "zone.js": "0.8.10"
  },
  "devDependencies": {
    "@ angular/cli": "1.0.3",
    "@ angular/compiler-cli": "4.1.2",
    "@ types/jasmine": "2.5.38",
    "@ types/node": "~6.0.60",
    "@ types/file-saver": "^0.0.0",
    "codelyzer": "2.0.1",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "4.5.1",
    "typescript": "2.2.2"
  }

**Comment by mmoravcik** [comment]
+1

**Comment by mmoravcik** [comment]
My mac error:


```
  ERROR in ENOENT: no such file or directory, open 
  '/<project_dir>/static/src/angular2/node_modules/@swimlane/ngx-
  dnd/release/components/container/container.component.html'

  ERROR in ./src/main.ts
  Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 
  '/<project_dir>/static/src/angular2/src'

```

**Comment by YannickLafont** [comment]
+1
Same problem.

**Comment by mmoravcik** [comment]
@Hypercubed any news on this? Are there going to be any Milestones for this project?

**Comment by Hypercubed** [comment]
I'm afraid don't know much about AOT.   Feedback from someone that knows how to get AOT working would be appreciated.

**Comment by mmoravcik** [comment]
Me neither, but had a quick look at the code and found this:

https://github.com/swimlane/ngx-dnd/blob/master/config/webpack.package.js#L77

commented out AOT code?

+ when I manually created some files as per screenshot, then `ng build --prod` has finished without errors...As the files are empty, I doubt it will actually work, but at least it builds..

![screen shot 2017-06-26 at 18 27 25](https://user-images.githubusercontent.com/600539/27551969-6bf84b42-5a9d-11e7-9e9a-52a0be15d499.png)

**Comment by YannickLafont** [comment]
@Hypercubed I can get AOT working when inlining templates and stylesheets (before switch scss to css) into the container and item component decorators. Then, there is no extra call to template or stylesheet files during AOT build on my projet.
Does anyone confirm this tip ? Hope you can publish a new version AOT ready.

**Comment by Hypercubed** [comment]
I was looking at this today.  AoT is still eluding me.

**Comment by Hypercubed** [comment]
AoT should b working now with v3.0.
