### ISSUE TITLE
Dragging and dropping in nested data causes data to be undefined - Directives

### ISSUE THREAD

**Issue by JayHelton** [swimlane/ngx-dnd#60]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

Dragging and dropping in nested data causes data to be undefined
**Expected behavior**

Dragging and dropping in nested data does not cause data to be undefined
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

Be able to style the directives easier than the components
**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

N/A
* **Angular version:** 2.x.x

newest
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

chrome is the only one i use
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 

code:

```
<h4>Program</h4>
    <div class="ngx-dnd-container" ngxDroppable [model]="targetBuilderTools" fxLayout="row" fxLayoutWrap="nowrap">
      <div fxFlex="45" class="ngx-dnd-item" ngxDraggable *ngFor="let model of targetBuilderTools">
        <p>Day {{targetBuilderTools.indexOf(model) + 1}}</p>
        <div class="ngx-dnd-container" ngxDroppable [model]="model.children">
          <div class="ngx-dnd-item" ngxDraggable *ngFor="let item of model.children; let i = index" [model]="item">{{item.name}} {{i}}</div>
        </div>
      </div>
    </div>
```

**Comment by Hypercubed** [comment]
Looks like you need to add a model in like three: `<div fxFlex="45" class="ngx-dnd-item" ngxDraggable *ngFor="let model of targetBuilderTools" [model]="model">`

**Comment by isawk** [comment]
I have a similar issue whiles attempting to create builder using directives, though modal is specified, in "grid", below input elements are not copied.

```html         
<ng-container *ngSwitchCase="'grid'">
    <div class="grid-x">
        <div class="cell large-auto medium-auto ngx-dnd-dropped-field-container_grid" dropZone="form-canvas" (drop)="elementDropped($event)" [removeOnSpill]="true" [model]="field.elements" ngxDroppable>
        </div>
        <div class="cell large-auto medium-auto ngx-dnd-dropped-field-container_grid" dropZone="form-canvas" (drop)="elementDropped($event)" [removeOnSpill]="true" [model]="field.elements" ngxDroppable>
        </div>
    </div>
</ng-container>
```

grid element 
```object 
{ name: 'Grid', type: "grid", descritpion: 'Grid layout', icon: 'grid_on', elements: [] as any[]}
```

In the above, onDrop logs show field.elements with expected value, however in ngxDroppable, dropped item is not cloned.

<img width="1285" alt="Screenshot 2019-05-21 at 16 22 25" src="https://user-images.githubusercontent.com/21027753/58104585-4d880d80-7be5-11e9-9ffd-d4b93c4cd8d4.png">

Image above shows that element [1] is successfully placed in Droppable, thus rendering [A], however when dropped in grid it is not rendered though it is successfully placed in [model]="field.elements"

<img width="793" alt="Screenshot 2019-05-21 at 16 25 04" src="https://user-images.githubusercontent.com/21027753/58104736-8c1dc800-7be5-11e9-8b89-8ff7f8df8dcd.png">

Image above shows that elements are successfully added to [model]="field.elements", however as indicated above render/copy doesn't work. Grid elements dropZone="form-canvas" same as over arching Droppable dropZone.
