### ISSUE TITLE
NullInjectorError: No provider for DroppableDirective

### ISSUE THREAD

**Issue by crutchcorn** [swimlane/ngx-dnd#62]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

When using `ngx-dnd-container`, I get the following errors thrown in my console when dragging an item:
```
VM57307 ExpansionOverviewExample.ngfactory.js:11 ERROR Error: StaticInjectorError(AppModule)[DraggableDirective -> DroppableDirective]: 
  StaticInjectorError(Platform: core)[DraggableDirective -> DroppableDirective]: 
    NullInjectorError: No provider for DroppableDirective!
```

* **ngx-dnd version:** 3.1.3

* **Angular version:** 5.2.8

**Comment by Hypercubed** [comment]
I suspect you are not properly including the module.  Can you send a plunkr/stackblitz example?

**Comment by lakinmohapatra** [comment]
I am facing same issue. Any help on this will be greatly appreciated.

**Comment by Hypercubed** [comment]
Please create a stackblitz...
