### ISSUE TITLE
Override CSS using Component

### ISSUE THREAD

**Issue by ignaciocaff** [swimlane/ngx-dnd#66]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

Im trying to override CSS class in order to change stlyes. While using cointainers.<ngx-dnd-container>
I tried 
.ngx-dnd-container {
  background-color: red;
}
In my CSS component file. Also i tried change background color directly in files
index.css, ngx-dnd.css, container.css, item.css and no results.
**Expected behavior**

Be able to change the styles used by library

**Reproduction of the problem**

Im trying to override CSS class in order to change stlyes. While using cointainers.<ngx-dnd-container>
I tried 
.ngx-dnd-container {
  background-color: red;
}
In my CSS component file. Also i tried change background color directly in files
index.css, ngx-dnd.css, container.css, item.css and no results.

**What is the motivation / use case for changing the behavior?**

Can customize the use.

**Please tell us about your environment:**

Windows, Visual CODE, 

* **ngx-charts version:** x.x.x

"@swimlane/ngx-dnd": "^3.1.3",

* **Angular version:** 2.x.x

"@angular/common": "^5.1.2",
    "@angular/compiler": "^5.1.2"

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES 6

**Comment by Hypercubed** [comment]
Can you create an example using plunkr or stackblitz?

**Comment by ignaciocaff** [comment]
Sure
https://embed.plnkr.co/x8l4Dmf4LKTikfIhWHoN/

The simplest implementation i could done. If you look in my .css file, im trying to change background color, and nothing happens.

As you can see, im using component way, not directive.

Thanks in advance

**Comment by Hypercubed** [comment]
If you are going to define CSS in your app component (as opposed to global) you will need to set `ViewEncapsulation.None`.  In addition, you will need to make your CSS more specific than the defaults.

See here: https://embed.plnkr.co/uNTvkV/

**Comment by ignaciocaff** [comment]
You are god. Greetings and thanks
