### ISSUE TITLE
Deep clone instead of shallow clone on copy

### ISSUE THREAD

**Issue by YungPablo** [swimlane/ngx-dnd#68]
**I'm submitting a feature imrpovement**

**Current behavior**
If copy is set to true it only creates a shallow copy

**Expected behavior**
If copy is set to true it should create a deep copy

**Possible fix**
Replace:
dropElmModel = JSON.parse(JSON.stringify(dropElmModel));
With:
dropElmModel = Object.assign({}, dropElmModel);

in services/drake-store.service.ts

**Comment by Hypercubed** [comment]
Well, `JSON.parse(JSON.stringify(dropElmModel))` is infact a deep clone, `Object.assign({}, dropElmModel);` is shallow.  We could explore a better deep clone tool.

**Comment by YungPablo** [comment]
My fault then, but it fixed an issue I had.
An object of mine had functions which are ignored by JSON and the "solution" provided above fixed it for me.

**Comment by Hypercubed** [comment]
Yes, the `JSON.parse(JSON.stringify(dropElmModel))` deep clone method does not handle some types.  In fact, all about deep clone methods I know of will not work with classes.  Becarefull with `Object.assign`, like I said it is not a deep clone.

I think your best bet is to do some refactoring of your code, if possible.  These type of models work best when the data is plain javascript objects.

**Comment by stockmind** [comment]
What about use lodash _.cloneDeep() method? It works like a charm with nested Types and custom classes

You just need to depend on:
```
@types/lodash
lodash
```

And include like:
```
import * as _ from "lodash";
```

to have it work like a charm!
