### ISSUE TITLE
How to Overwrite The Default Css Of ngx-dnd-container ? Please help

### ISSUE THREAD

**Issue by Souvik93** [swimlane/ngx-dnd#7]

**Comment by Hypercubed** [comment]
You can easily override the `.ngx-dnd-item` and `.ngx-dnd-container` classes.  Be aware of CSS specificity rules: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity .

In general I would encourage using the ngx-dnd directives vs. the components.

**Comment by Souvik93** [comment]
Ok. How Can I use ngx-dnd directive instead of <ngx-dnd-container> in the  "Builder Demo" example (last one) ?
[ngx-dnd.txt](https://github.com/swimlane/ngx-dnd/files/1043863/ngx-dnd.txt)

**Comment by Hypercubed** [comment]
Use the `.ngx-dnd-item` and `.ngx-dnd-container` classes. If they don't work then you need to make the CSS selector more specific... for example using `!important`.

You use the directives like this:

```
<div class="ngx-dnd-container" ngxDroppable>
  <div class="ngx-dnd-item" ngxDraggable>Item 1</div>
  <div class="ngx-dnd-item" ngxDraggable>Item 2</div>
  <div class="ngx-dnd-item" ngxDraggable>Item 3</div>
</div>
```

IN which case you can use any class you like.

**Comment by Souvik93** [comment]
Thanks a lot. My css issue is solved ri8 now. :)

**Comment by sumitmatta998** [comment]
+1
@Souvik93  can you explain which css you use?

**Comment by CodingGorilla** [comment]
So like @Souvik93 I am trying to build something very similar to the "Builder Demo", but I want to use directives rather than the components (since the styling on the components is hard coded and very difficult to override).  

@Hypercubed can you offer any advice on how to reproduce this demo with directives?  I can't seem to make it work quite right without getting errors similar to #44 .

**Comment by frankpaap** [comment]
Use encapsulation: ViewEncapsulation.None; in component. See below
`@Component({
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.scss'],
  encapsulation: ViewEncapsulation.None;
})
`
Use this in your component (s)css:
`
.ngx-dnd-container{
  background: red !important;
}
`
