### ISSUE TITLE
Support for use drag and drop with table

### ISSUE THREAD

**Issue by prashant-shilimkar** [swimlane/ngx-dnd#70]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```
Hi,
Is there any way to use drag and drop feature with a table in Bootstrap 4. So I can drag and drop row of a table to sort a model array. If not then do you have any plan for that. 

Thank you. You are doing great work :)

**Comment by Hypercubed** [comment]
It's certainly possible.  Just use the directives on the table elements.  If you get stuck post a plunkr/stack blitz example.
