### ISSUE TITLE
Support Angular 6 and rxjs 6

### ISSUE THREAD

**Issue by janKir** [swimlane/ngx-dnd#76]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

When running `ng update @angular/core` it says:
`Package "@swimlane/ngx-dnd" has an incompatible peer dependency to "rxjs" (requires "^5.4.0", would install "6.1.0").`

**Expected behavior**

Being able to update to Angular 6 without imcompability errors.

**Reproduction of the problem**

Install Angular 5 and @swimlane/ngx-dnd 3.2.0, then try to [update to Angular 6](https://update.angular.io/).

**Please tell us about your environment:**

* **ngx-charts version:** 3.2.0

* **Angular version:** 6.0.0

**Comment by Hypercubed** [comment]
Will be done soon.... Waiting on a Dev dep to get published.

**Comment by crutchcorn** [comment]
This has been finished with release of 4

**Comment by Hypercubed** [comment]
yes... this is done, release in v4.x
