### ISSUE TITLE
AOT build can't find container.component.css

### ISSUE THREAD

**Issue by ssuperczynski** [swimlane/ngx-dnd#86]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**
```
Building Angular Package
Building entry point 'ngx-easy-table'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc

BUILD ERROR
: Couldn't resolve resource ./container.component.css relative to /Users/sebastian/WebstormProjects/project/node_modules/@swimlane/ngx-dnd/release/src/components/container/container.component.d.ts
```

**Expected behavior**
How to fix it. Go to package.json and change lines to:

```
"copy:html": "cpx \"src/**/*.html\" release/src",
"build": "webpack --display-error-details",
"build:sass": "node-sass -r src/ -o release/src",
```

**Reproduction of the problem**
Since project is not using angular-cli and ng-packagr it is unable to reproduce this error in the project itself. It is possible when you add it to project's dependencies that use ng-packagr.

**What is the motivation / use case for changing the behavior?**
Project that use ngx-dnd ad a dependency can't compile.

**Please tell us about your environment:**
Mac Os High Sierra

* **ngx-dnd version:** x.x.x
4.0.2

* **Angular version:** 2.x.x
6.02

* **Language:** TypeScript 2.7.2

**Comment by Hypercubed** [comment]
@ssuperczynski Can you please try installing teh next version, see if that solves your issues: `npm install @swimlane/ngx-dnd@next`

**Comment by ssuperczynski** [comment]
@Hypercubed I can confirm this issue no longer exists after installing `@swimlane/ngx-dnd@next`

**Comment by Hypercubed** [comment]
@ssuperczynski Thank you!
