### ISSUE TITLE
SASS styles

### ISSUE THREAD

**Issue by GeraldAburto** [swimlane/ngx-dnd#87]
I'm using sass on my Angular prioject
I tried
 "styles": [
        "styles.sass",
        "@swimlane/ngx-dnd/release/index.css"
      ]
but it seems not to work
It would be great if you included the .scss file for styles

**Comment by Hypercubed** [comment]
Can you please try the4 next version `npm install @swimlane/dragula @swimlane/ngx-dnd@next` it includes both the CSS and SCSS.

**Comment by Hypercubed** [comment]
Just published 5.0.2, if you still see this issue please reopen.
