### ISSUE TITLE
Building with --aot flag is broken after updating version from 4.0.1 to 4.0.2

### ISSUE THREAD

**Issue by tama3bb** [swimlane/ngx-dnd#88]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

The following error occurs when building an Angular 6 based application by `ng build --aot` with ngx-dnd version 4.0.2.

```
ERROR in : Unexpected value 'NgxDnDModule in /xxx/node_modules/@swimlane/ngx-dnd/release/index.js' imported by the module 'XxxModule in /Users/xxx/src/app/xxx/xxx.module.ts'. Please add a @NgModule annotation.
```

Some directories such as directives and services seem to be missing under the release directory.

<img width="195" alt="version 4.0.2" src="https://user-images.githubusercontent.com/638201/40534164-12b4be18-6040-11e8-98d8-0b7e76f78edb.png">

**Expected behavior**

No error occurs when building the same Angular 6 based application by `ng build --aot` with ngx-dnd version 4.0.1.

See the image below.

<img width="304" alt="version 4.0.1" src="https://user-images.githubusercontent.com/638201/40534183-25f7dd2a-6040-11e8-818b-019dde932acf.png">

**Reproduction of the problem**

N/A

**What is the motivation / use case for changing the behavior?**

N/A

**Please tell us about your environment:**

* **ngx-dnd version:** 4.0.2

* **Angular version:** 6.0.3

* **Browser:** N/A

* **Language:** TypeScript 2.7.2

**Comment by Gerros** [comment]
true story... not only the aot build is broken, ng serve etc. as well

**Comment by smiper** [comment]
Isn't "ng build --prod" broken too with the same error (Unexpected value 'NgxDnDModule). 

It seems to me that AOT building is broken in 4.0.1 and 4.0.2. Although 4.0.0 seems to be working for me.

**Comment by Hypercubed** [comment]
@tama3bb @smiper Can any of you try installing the next version... I hope it will fix your issues.  `npm install @swimlane/ngx-dnd@next`

**Comment by tama3bb** [comment]
@Hypercubed I have tried installing the next version `@swimlane/ngx-dnd@next` and it has worked. I had to install `@swimlane/dragula` module.

**Comment by Hypercubed** [comment]
Yes, thank you for testing.  `@swimlane/dragula` is now a peer... I'll be adding that to the docs.
