### ISSUE TITLE
Couldn't resolve resource ./container.component.css

### ISSUE THREAD

**Issue by bostondevin** [swimlane/ngx-dnd#95]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

Fresh install / build produces this:
ERROR in : Couldn't resolve resource ./container.component.css relative to /Users/bostondevin/websites/gizmo/node_modules/@swimlane/ngx-dnd/release/src/components/container/container.component.d.ts

It's referring to files in a completely different directory (/ngx-dnd/components/container/...) so moving the files into that directory fixes the issue

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Latest CLI, Angular version

* **ngx-dnd version:** x.x.x

Latest

* **Angular version:** 2.x.x

Latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by Hypercubed** [comment]
@bostondevin Can you please give the next version a try: `npm install @swimlane/ngx-dnd@next`

**Comment by bostondevin** [comment]
That works great - thanks!!!
