### ISSUE TITLE
Manually delete an item from dndModel

### ISSUE THREAD

**Issue by neil-coutinho** [swimlane/ngx-dnd#96]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

I am trying to manually delete an item in the dndModel by clicking a remove icon, instead of dragging it our of the dropzone. How do I get the index of the clicked item or use the DrakeStoreService's remove function()

**Please tell us about your environment:**

MacOS Sierra, Atom IDE, Angular CLI v6.0.3, Angular 6

* **ngx-dnd version:** x.x.x

^4.0.1
* **Angular version:** 2.x.x

6.0.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by ssuperczynski** [comment]
@neil-coutinho I use these events to manipulate dndModel

```html
<div class="ngx-dnd-container" ngxDroppable
  (drag)="log($event)"
  (drop)="log($event)"
  (over)="log($event)"
  (out)="log($event)"
  (remove)="log($event)">
  <div class="ngx-dnd-item" ngxDraggable>Item 1</div>
  <div class="ngx-dnd-item" ngxDraggable>Item 2</div>
  <div class="ngx-dnd-item" ngxDraggable>Item 3</div>
</div>
```

**Comment by neil-coutinho** [comment]
@ssuperczynski right! However, the remove handler is only called if I drag an item out of the dropzone. 

`<div class="ngx-dnd-container" ngxDroppable
  (drag)="log($event)"
  (drop)="log($event)"
  (over)="log($event)"
  (out)="log($event)"
  (remove)="log($event)">
  <div class="ngx-dnd-item" ngxDraggable>Item 1 <a (click)="removeItem()">x</a></div>
  <div class="ngx-dnd-item" ngxDraggable>Item 2 <a (click)="removeItem()">x</a></div>
  <div class="ngx-dnd-item" ngxDraggable>Item 3 <a (click)="removeItem()">x</a></div>
</div>`

I wanted to know if there is a way I can manually w/o dragging the item, click a link and call a custom removeItem method which in turn removed the item from the [model]

**Comment by Hypercubed** [comment]
Maybe I don't understand... but can't you just add a delete button, like you would without ngx-dnd.

**Comment by neil-coutinho** [comment]
```
<ngx-dnd-container [model]="dndModel" dropZone="model-designer" [removeOnSpill]="true">

    <ng-template let-model="model" let-template="template">
      <!-- ngx-dnd-item html goes here -->
   </ng-template>

 </ngx-dnd-container>
```
@Hypercubed Thank you for getting back, 
I only have access to the local template and model variables. Without an index or id it would not be possible to search the model array for an item  Or do I simply traverse the entire model and search for the item where item === model  and splice it out?

Can one use the DrakeStoreService functions for this?

**Comment by caleywoods** [comment]
@neil-coutinho Whatever elements are making up your drag and drop items are being created within your component file and likely being output in your HTML by an `*ngFor`. You can access the index of an `ngFor` item, here's how I handle exactly what you're doing:

```
<div class="display-filters-list">
    <mat-chip-list>
        <mat-chip *ngFor="let f of currentFilters; let i = index">{{f}} <i class="fa fa-remove" (click)="removeFilter(i)"></i></mat-chip>
    </mat-chip-list>
</div>
```

Then in the components ts file:

```
// Remove the filter via its index position coming from the click event on the "x" in the UI
removeFilter(idx): void {
    const newFilters = this.currentFilters.filter( (filter,index) => {index !== idx} );
    this.currentFilters = [...newFilters];
}
```

There's nothing needed from ngx-dnd here, it's all plain JS/TS. Ignore the `<mat>` elements, those are just material components and could be divs or li's within a ul just as easily.

**Comment by neil-coutinho** [comment]
@caleywoods @Hypercubed Thanks for the above. This works perfectly if you have a simple one dimensional model, However if you have a nested sortable model like [here](https://swimlane.github.io/ngx-dnd), looks like the only method is to use the component way which does not use the index

```
nestedLists = [
  {
    "label": "Item 1",
    "children": []
  },
  {
    "label": "Item 2",
    "children": [
      {
        "label": "Item 2a",
        "children": []
      },
      {
        "label": "Item 2b",
        "children": []
      },
      {
        "label": "Item 2c",
        "children": []
      }
    ]
  },
  {
    "label": "Item 3",
    "children": [
      {
        "label": "Item 3a",
        "children": []
      },
      {
        "label": "Item 3b",
        "children": []
      },
      {
        "label": "Item 3c",
        "children": []
      }
    ]
  }
]
```
```
<ngx-dnd-container
  [model]="nestedLists">
</ngx-dnd-container>
```

**Comment by Hypercubed** [comment]
@neil-coutinho We could consider adding an index, but I feel in general if you are doing anything more complex then simple DnD lists, you should use the directives.

You can the directives with nested lists.  Unfortunately, we don't have a good example of this at the moment.

**Comment by devwals** [comment]
I am also trying to delete the items using a button within the items. I still like the drag outside to delete but for usability I will be adding a button in the items to delete them on click. I was thinking of traversing using the tree using a recursive function and then remove the item but right now I am looking at the ngx-dnd directives to see if I can copy the remove function. 

It'd be great if you can point me in the right direction.

**Comment by guddu-patel** [comment]
I am also trying to delete the items using a button within the multiple items list. any help will be appreciated.
Thanks in advance
