### ISSUE TITLE
https://swimlane.github.io/ngx-dnd/ Is Down

### ISSUE THREAD

**Issue by term29** [swimlane/ngx-dnd#99]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**

https://swimlane.github.io/ngx-dnd/ is timing out and cannot be reached.
**Expected behavior**

https://swimlane.github.io/ngx-dnd/ loads.
**Reproduction of the problem**

In the latest Google Chrome, browse to https://swimlane.github.io/ngx-dnd/.  Site fails to load and the following message is displayed: "This site can’t be reached. swimlane.github.io took too long to respond."
**What is the motivation / use case for changing the behavior?**

I need to reference the samples for a project on a strict deadline.  (Thanks for the great DnD library btw!)
**Please tell us about your environment:**

Windows 10. Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
* **ngx-dnd version:** x.x.x

4.0.1

* **Angular version:** 2.x.x

Angular CLI 6.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.7.2

**Comment by Hypercubed** [comment]
I'm not seeing this issue.

**Comment by term29** [comment]
Thanks for the quick response. 

Currently, the site doesn't load over my work network, and is reported as "down for everyone" by https://downforeveryoneorjustme.com/.  

However, the site does load when tethered to my cell network.  Perhaps a dns issue.

**Comment by Hypercubed** [comment]
I think downforeveryoneorjustme.com is not reliable in this case.  It only checks the domain.  As far as I can tell it is up and running.  It might be a caching issue on your end.

**Comment by term29** [comment]
I found that they have been messing with filters at the office and inadvertently blocked https://github.com/swimlane/ngx-dnd.  Apologies for the false alarm.

**Comment by Hypercubed** [comment]
No worries, thank you for trying to keep us up!
